#!/usr/bin/env bash
#     _         _         __        ______
#    / \  _   _| |_ ___   \ \      / /  _ \
#   / _ \| | | | __/ _ \   \ \ /\ / /| |_) |
#  / ___ \ |_| | || (_) |   \ V  V / |  __/
# /_/   \_\__,_|\__\___/     \_/\_/  |_|
#

xcloud_cache_folder="$HOME/.cache/xcloud/hyprland-dotfiles"

# Notifications
source "$HOME/.config/xcloud/scripts/xcloud-notification-handler"
APP_NAME="Waypaper"
NOTIFICATION_ICON="preferences-desktop-wallpaper-symbolic"

sec=$(cat ~/.config/xcloud/settings/wallpaper-automation)
_setWallpaperRandomly() {
    while true; do
        $HOME/.config/xcloud/scripts/xcloud-wallpaper --random
        echo ":: Next wallpaper in $sec seconds..."
        sleep $sec
    done
}

if [ ! -f $xcloud_cache_folder/wallpaper-automation ]; then
    touch $xcloud_cache_folder/wallpaper-automation
    echo ":: Start wallpaper automation script"
    notify_user \
        --a "${APP_NAME}" \
        --i "${NOTIFICATION_ICON}" \
        --m "Wallpaper automation process started.\nWallpaper will be changed every $sec seconds."
    _setWallpaperRandomly
else
    rm $xcloud_cache_folder/wallpaper-automation
    notify_user \
        --a "${APP_NAME}" \
        --i "${NOTIFICATION_ICON}" \
        --m "Wallpaper automation process stopped."
    echo ":: Wallpaper automation script process $wp stopped"
    wp=$(pgrep -f xcloud-wallpaper-automation)
    kill -KILL $wp
fi
