-- Generated by nwg-displays on 2026-08-31 at 08:32:56. Do not edit manually.

hl.monitor({
    output = "desc:AU Optronics 0x6693",
    mode = "1920x1200@60.03",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10,
    vrr = 1
})
