-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 15,
    },
    misc = {
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
    },
})

-- Monitors
hl.monitor({
    output = "desc:AU Optronics 0x6693",
    disabled = false,
    mode = "1920x1200@60.03Hz",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    cm = "srgb",
})
